[tasks.dev-backend]
script = """
cd server && cargo watch -- cargo run
"""

[tasks.dev-frontend]
script = """
cd client && pnpm dev
"""

[tasks.dev-server]
run_task = { name = ["dev-frontend", "dev-backend"], parallel = true }

[tasks.dev-start-db]
script = """
cd server && docker-compose up -d
"""

[tasks.dev]
run_task = { name = ["dev-start-db", "dev-server"], parallel = false }
