//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.0-rc.2

pub mod prelude;

pub mod circle;
pub mod genre;
pub mod product;
pub mod product_genre;
pub mod product_user_genre;
pub mod sea_orm_active_enums;
pub mod user;
