//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.0-rc.2

pub use super::circle::Entity as Circle;
pub use super::genre::Entity as Genre;
pub use super::product::Entity as Product;
pub use super::product_genre::Entity as ProductGenre;
pub use super::product_user_genre::Entity as ProductUserGenre;
pub use super::user::Entity as User;
