//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, rspc::Type,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "age")]
pub enum Age {
    #[sea_orm(string_value = "Adult")]
    Adult,
    #[sea_orm(string_value = "All")]
    All,
    #[sea_orm(string_value = "R")]
    R,
}
