env_files = [".env"]

[config]
default_to_workspace = false
unstable_features = ["CTRL_C_HANDLING"]

[tasks.dev-backend]
script = "cargo run"
watch = true

[tasks.dev-frontend]
script = "cd ../client && pnpm dev"

[tasks.dev-server]
run_task = { name = ["dev-frontend", "dev-backend"], parallel = true }

[tasks.db-up]
script = "docker-compose up -d"

[tasks.dev]
run_task = { name = ["db-up", "dev-server"], parallel = false }

[tasks.entity-gen]
script = """
sea generate entity -u postgresql://sample:password@localhost:5432/db -o entity/src/entities/ --with-serde both  --model-extra-derives "rspc::Type"
"""

[tasks.mg-fresh]
script = "sea migrate fresh"

[tasks.mg]
script = "sea migrate ${@}"

[tasks.build-frontend]
script = "cd ../client && pnpm build"
[tasks.copy-asset]
script = "rm -rf ./assets && cp -r ../client/dist ./assets"
[tasks.docker-build]
script = "docker build -t dap:latest ."
dependencies = ["build-frontend", "copy-asset"]

[tasks.run-release]
script = "cargo run --release"
dependencies = ["build-frontend", "copy-asset"]
