[config]
default_to_workspace = false

[tasks.dev-backend]
script = "cargo watch -- cargo run"

[tasks.dev-frontend]
script = "cd ../client && pnpm dev"

[tasks.dev-server]
run_task = { name = ["dev-frontend", "dev-backend"], parallel = true }

[tasks.db-up]
script = "docker-compose up -d"

[tasks.dev]
run_task = { name = ["db-up", "dev-server"], parallel = false }

[tasks.genquery]
script = """
cornucopia live "postgresql://sample:password@localhost:5432/db"
rustfmt --edition 2021 ./src/cornucopia.rs
"""

[tasks.migrate]
script = """
atlas schema apply --url "postgresql://sample:password@localhost:5432/db?sslmode=disable" --to "file://schema.hcl"
"""
dependencies = ["db-up"]

[tasks.build-frontend]
script = "cd ../client && pnpm build"
[tasks.copy-asset]
script = "rm -rf ./assets && cp -r ../client/dist ./assets"
[tasks.docker-build]
script = "docker build -t dap:latest ."
dependencies = ["build-frontend", "copy-asset"]
