[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sea-orm = { version = "0.12.0-rc.2", features = ["postgres-array"] }
rspc = { version = "0.1", features = ["chrono"] }
serde = "1"
