DROP TABLE IF EXISTS "product_creator";
DROP TABLE IF EXISTS "creator";
DROP TYPE IF EXISTS "creator_role";
DROP TABLE IF EXISTS "product_user_genre";
DROP TABLE IF EXISTS "product_genre";
DROP TABLE IF EXISTS "genre";
DROP TRIGGER IF EXISTS "product_update" ON "product";
DROP FUNCTION IF EXISTS set_updated_at();
DROP TABLE IF EXISTS "product";
DROP TYPE IF EXISTS "age_category";
DROP TABLE IF EXISTS "circle";
DROP TABLE IF EXISTS "user";
