/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "config.getScandir", input: never, result: string[] } | 
        { key: "ping", input: never, result: string } | 
        { key: "ping_auth", input: never, result: string },
    mutations: 
        { key: "config.setPassword", input: string, result: string } | 
        { key: "config.setScandir", input: string[], result: string } | 
        { key: "product.get", input: never, result: null } | 
        { key: "scan.start", input: never, result: null },
    subscriptions: never
};
